spring.application.name=ktrac

# DB properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ktrac
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway
spring.flyway.enabled=true

# Security Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ktrac

keycloak.server-url=http://localhost:8080
keycloak.realm=ktrac
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin
