spring.application.name=ktrac

# DB properties
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ktrac}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Flyway
spring.flyway.enabled=true

# Security Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/ktrac}

keycloak.server-url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:ktrac}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:admin-cli}
keycloak.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
