CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES
('ADMIN'),
('PRODUCTION_MANAGER'),
('LOCO_SHED_MANAGER'),
('TECHNICIAN'),
('KERNEX_SUPERVISOR'),
('RAILWAY_USER'),
('AUDITOR');
